### ISSUE TITLE
pandas to nicecx does not allow control of represents vs. name

### ISSUE THREAD

**Issue by dexterpratt** [ndexbio/ndex2-client#13]
we need several of the features of the tsv load plan, should probably integrate and have TSV loader utilities just be a wrapper.

**Comment by agary-ucsd** [comment]
Agreed.  We should look into having TSV loader utils be a wrapper

**Comment by coleslaw481** [comment]
Please take a look at 3.8.0 ndex2 client see if https://ndex2.readthedocs.io/en/latest/cx2.html#ndex2.cx2.PandasDataFrameToCX2NetworkFactory.get_cx2network
meets your needs. If not please open a new issue.
