### ISSUE TITLE
Documented version doesn't reflect software version

### ISSUE THREAD

**Issue by cthoyt** [ndexbio/ndex2-client#14]
While the release is called version 1.0, the software version seems to be '0.2.0.29'. This is a bit confusing.

https://github.com/ndexbio/ndex2-client/blob/376aab30e3e6d1d70f1e14f782bfce260a325631/setup.py#L26

https://github.com/ndexbio/ndex2-client/blob/376aab30e3e6d1d70f1e14f782bfce260a325631/docs/conf.py#L64

Additionally, neither of these versioning schemes adheres to [semantic versioning](https://semver.org/). That's okay, but adhering to community standards makes it easier to navigate projects.

**Comment by agary-ucsd** [comment]
Documentation is being updated with the release of v2.0.0
