### ISSUE TITLE
NetworkX Version

### ISSUE THREAD

**Issue by stevencox** [ndexbio/ndex2-client#23]
Hi Folks,

I'm using NDEx via the ndex2 Python client but I can't include the functionality in my pip installable deliverable.

My code uses Networkx 2.2 but ndex2 relies on a 1.x version.

Will there be a new release soon with a more modern NetworkX?

**Comment by agary-ucsd** [comment]
HI Steve, thanks for posting this.  We are releasing a new version this week that will lift the dependance on V1.11 of networkx.  I'll ping you when we release.

**Comment by stevencox** [comment]
Great. Thanks.

**Comment by agary-ucsd** [comment]
Hey Steve, we released a new networkx 2.x compatible version.  The latest version is 2.0.0.1.  A few things changed internally in this version, but hopefully it won't break your code.  Here is our latest documentation:

http://www.home.ndexbio.org/ndex2-sphinx/docs/ndex2.html

https://github.com/ndexbio/ndex-jupyter-notebooks/blob/master/notebooks/NiceCX%20v2.0%20Tutorial.ipynb

Thanks,
  Aaron

**Comment by stevencox** [comment]
Thanks @agary-ucsd  - that's good news.

Interestingly, it doesn't throw any errors. But it also doesn't create the network. 

Here are screenshots with details.

![image](https://user-images.githubusercontent.com/306971/46704865-f061bd80-cbfa-11e8-9d2d-6fb9bcc070c6.png)

Details from one of the above errors:

![image](https://user-images.githubusercontent.com/306971/46704877-01aaca00-cbfb-11e8-989a-663cceb7d823.png)

What do you think?

**Comment by agary-ucsd** [comment]
It appears that it didn't create any nodes, but it's hard to tell why.  Can you share your code?  My email is agary@ucsd.edu.

Thx

**Comment by stevencox** [comment]
My bad. Something upstream had changed. The new client works great with with my old code. No changes required. Thanks.

**Comment by zachary822** [comment]
NetworkX has dropped support for python 2 after version 2.2. Either lock NetworkX version to <= 2.2 or drop python 2 support for this package as well?

**Comment by coleslaw481** [comment]
Thanks for letting me know. I missed the note about dropping python 2 for networkx 2.3. 

I'm hoping to avoid locking the networkx version and instead just have this client check the version of networkx and act appropriately.
