### ISSUE TITLE
Add get_networksets() method

### ISSUE THREAD

**Issue by coleslaw481** [ndexbio/ndex2-client#61]
Add a method that lets caller get a list of network sets owned by them or another user (assuming permissions allow this)

Jing suggested the following

> It will be good to add it in. A list of networksets owned by the authenticated user or any users? Maybe the signature can be an optional uuid, without the uuid, is the current user, with the UUID is for other users?

**Comment by ariutta** [comment]
This would also be useful for me. I'm trying to remove all my networks that are not in at least one networkset.

**Comment by coleslaw481** [comment]
The endpoint to use for this. 
http://openapi.ndextools.org/#/User/get_user__userid__networksets

**Comment by coleslaw481** [comment]
Added `Ndex2.get_networksets_for_user_id` to upcoming `3.4.0` of ndex2 client. Currently available to try as an alpha version by running `pip install ndex2==3.4.0a1` For usage see: https://ndex2.readthedocs.io/en/latest/ndex2client.html#ndex2.client.Ndex2.get_networksets_for_user_id
