### ISSUE TITLE
Extensibility of type assertions

### ISSUE THREAD

**Issue by cthoyt** [ndexbio/ndex2-client#7]
Use `instanceof(X, Y)` instead of `type(X) is Y` to make classes extensible. Reference: https://stackoverflow.com/a/2225066/5775947

https://github.com/ndexbio/ndex2-client/blob/64d3fad534ce7b41427106d2e9a37b6bfcedaaef/nicecxModel/NiceCXNetwork.py#L95

**Comment by agary-ucsd** [comment]
Changed all type() to isinstance()
