### ISSUE TITLE
Question: is uuid unique to each version?

### ISSUE THREAD

**Issue by RemyLau** [ndexbio/ndex2-client#86]
I'm working on a package that interfaces with ndex2 for retrieving networks. I've written a few small tests using some small networks available on NDEX via uuid, but I'm not totally sure whether uuid is unique to a specific version of the network. If it is not unique, i.e. the network associated with a uuid might change over time, then I might need to rewrite some of my tests. Thanks for any help in advance!

**Comment by coleslaw481** [comment]
It is not unique for each version cause it is possible to update a network and keep the same UUID: https://ndex2.readthedocs.io/en/latest/ndex2client.html#ndex2.client.Ndex2.update_cx_network

**Comment by RemyLau** [comment]
Thanks a lot!
