### ISSUE TITLE
ndex2 on conda

### ISSUE THREAD

**Issue by MOohTus** [ndexbio/ndex2-client#94]
Hello, 

I created a tool that is using your ndex2 python package to request NDEx.
I would like to make my tool available on bioconda but I currently can't do it because ndex2 is not avaiblable there.
Would you be able to make ndex2 available on bioconda or conda?

Thank you!

Morgane

**Comment by coleslaw481** [comment]
Very cool. 

That is a good idea to get ndex2 on conda. I see they have [instructions](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html). I am just swamped with other tasks right now so I'm not sure when I'll get to it.

**Comment by MOohTus** [comment]
Hello, 

ndex2 is now available on [bioconda](https://anaconda.org/bioconda/ndex2])!

**Comment by coleslaw481** [comment]
Cool. Thank you. When we have a new version, how do we update this?
